### ISSUE TITLE
Step failure with Xcode 16.0 stack

### ISSUE THREAD

**Issue by oronbz** [kishikawakatsumi/bitrise-step-xcode-result-bundle-to-checks#48]
After upgrading to bitrise stack to Xcode 16 this step no longer works:

```
++ uuidgen
+ INPUT_PATH=/var/folders/b8/9zt_tx3s1y37nzh_cs991xyc0000gn/T/XCUITestOutput821770615/Test-GetTaxi-INT-QA.xcresult
+ INPUT_TITLE='Xcode test results'
+ env INPUT_SHOW-PASSED-TESTS=true env INPUT_SHOW-CODE-COVERAGE=true 'INPUT_TITLE=Xcode test results' INPUT_GITHUB_OWNER=gtforge INPUT_GITHUB_REPO=gtforge-iphone INPUT_GITHUB_SHA=f04f865782e68aebdeff4976fdbbd9353339ef8e INPUT_TOKEN=34C10977-8258-4BFC-AC00-87AEA5C6DCAF node --unhandled-rejections=strict /var/folders/b8/9zt_tx3s1y37nzh_cs991xyc0000gn/T/bitrise2041728818/step_src/dist/index.js
/private/var/folders/b8/9zt_tx3s1y37nzh_cs991xyc0000gn/T/bitrise2041728818/step_src/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
^
Error: The process '/usr/bin/xcrun' failed with exit code 64
    at ExecState._setResult (/private/var/folders/b8/9zt_tx3s1y37nzh_cs991xyc0000gn/T/bitrise2041728818/step_src/node_modules/@actions/exec/lib/toolrunner.js:592:1)
    at ExecState.CheckComplete (/private/var/folders/b8/9zt_tx3s1y37nzh_cs991xyc0000gn/T/bitrise2041728818/step_src/node_modules/@actions/exec/lib/toolrunner.js:575:1)
    at ChildProcess.<anonymous> (/private/var/folders/b8/9zt_tx3s1y37nzh_cs991xyc0000gn/T/bitrise2041728818/step_src/node_modules/@actions/exec/lib/toolrunner.js:469:1)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:338:12)

```

Please LMK if you need any other information, this step is crucial to us.

**Comment by dppeak** [comment]
Getting the same thing here.  Step is unusable at this point.

Following...

**Comment by rgg-clineu** [comment]
same here

**Comment by lfarah** [comment]
same here
